"""empty message

Revision ID: 2b17320d433b
Revises: 0aa2a8d3587c
Create Date: 2016-04-17 20:18:43.024427

"""

# revision identifiers, used by Alembic.
revision = '2b17320d433b'
down_revision = '0aa2a8d3587c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
