"""empty message

Revision ID: 77fd0b721bdb
Revises: 01a38fa86519
Create Date: 2016-04-12 19:52:32.395991

"""

# revision identifiers, used by Alembic.
revision = '77fd0b721bdb'
down_revision = '01a38fa86519'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
